# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a869d00543a9812938c1bfcc426aac09ac5fa76101d8a8a91ce007f524cbb607e9689b5100947fc7ffac476933ef7e13f8ed1cb6e4f8ba85671ddbc38bd641d

test:
  secret_key_base: a9c1f7cb9eb52f798d09aad752456f8b7e197ef29bb726a195c5f406c63a7713a427eed57b1dd1c26a7cab8e283090dd3c12d1718ea34751c5f76a984ae4c949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
